import React from 'react'

const DisclaimerWarranties = () => {
    const body = `Collegeshala does not provide any warranties, express or implied, or make any representations regarding the use, or the results of use, of CONTENT, in terms of its correctness, legality, decency, accuracy, reliability, appropriateness or otherwise. Review and use of CONTENT are subject to all applicable laws and regulations and is solely at the risk of the individual or organization using this data.\n
    CollegeShala MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, LACK OF VIRUSES OR OTHER HARMFUL COMPONENTS AND ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES, GRAPHICS AND ANY OTHER MATERIAL AND CONTENT THAT YOU ACCESS VIA THE ";SERVICE"; FOR ANY PURPOSE. ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES, GRAPHICS, AND ANY OTHER MATERIAL AND CONTENT ARE PROVIDED ";AS IS"; WITHOUT WARRANTY OF ANY KIND.\n
    YOU EXPRESSLY UNDERSTAND AND AGREE THAT:\n
    a. YOUR USE OF THE "SERVICE" IS AT YOUR SOLE RISK. THE "SERVICE" IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. CollegeShala EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.\n
    b. CollegeShala MAKES NO WARRANTY THAT (i) THE "SERVICE" WILL MEET YOUR REQUIREMENTS, (ii) THE "SERVICE" WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE"SERVICE" WILL BE ACCURATE OR RELIABLE, (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE "SERVICE" WILL MEET YOUR EXPECTATIONS, (v) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED, (vi) THE "CONTENT" OR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES, GRAPHICS AND ANY OTHER MATERIAL DELIVERED TO YOU VIA THE "SERVICE" WILL HAVE NO VIRUSES OR OTHER HARMFUL COMPONENTS, AND (vii) THE USE OF USERNAMES, PASSWORDS, COOKIES AND OTHER DESIGN ELEMENTS OF THE WEBSITE WILL BE SECURE AND IMMUNE FROM SECURITY THREATS.\n
    c. THE USE OF COOKIES, USERNAMES AND PASSWORDS ON THE WEBSITE; YOUR PROVISION OF PERSONAL AND CONFIDENTIAL INFORMATION SUCH AS HOME ADDRESS, EMPLOYER INFORMATION, AND E-MAIL ADDRESSES; PLUS ALL OTHER FEATURES OF THIS WEBSITE INCLUDING, BUT NOT LIMITED TO, THE "REMEMBER ME" FACILITY : ANY AND ALL OF THESE FEATURES AND FACILITIES COULD POTENTIALLY EXPOSE YOU AND YOUR COMPUTER TO SECURITY THREATS. YOU SHOULD CONSIDER THESE RISKS BEFORE MAKING A DECISION TO ACCESS THIS WEBSITE AND ITS "CONTENT", AND TO USING ANY OF THE "SERVICES", ALL OF WHICH ARE PROVIDED SOLELY AT YOUR RISK.\n
    d. ANY "CONTENT" OR OTHER MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE "SERVICE" IS DONE AT YOUR DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA CollegeShala A THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.\n
    e. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM OR THROUGH OR FROM THE "SERVICE" SHALL CREATE ANY WARRANTY.\n
    YOU EXPRESSLY UNDERSTAND AND AGREE THAT CollegeShala SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF CollegeShala.IN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE USE OR THE INABILITY TO USE THE "SERVICE"; (ii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE "SERVICE"; (iii) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (iv) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE "SERVICE"; OR (v) ANY OTHER MATTER RELATING TO THE"SERVICE".\n
    All materials are available at CollegeShala are contributed by users, and the ownership and copyright to the materials remain with the actual owner of the content. CollegeShala does not claim ownership of any materials or Intellectual Property. Materials shared at CollegeShala.in are available for educational purposes only. No claim for the originality of content is made. The contents are shared by the users to help other community members.`
    return (
    <div>
        <div class="container text-center py-3">
            <h2>DISCLAIMER OF WARRANTIES</h2>
            <div class="text-left">
                <p style={{whiteSpace : "pre-line"}}>{body}</p>
            </div>
        </div>
    </div>
    );
}

export default DisclaimerWarranties